// workers-types v5 types `env` as `Cloudflare.Env` and expects projects to extend it by
// declaration merging (it replaced vitest-pool-workers' old `ProvidedEnv` interface).
// Kept hand-written rather than generated by `wrangler types`, so the test bindings that
// exist only under vitest — TEST_MIGRATIONS, and a SESSION_SECRET that never comes from
// .dev.vars — stay visible next to the ones wrangler.jsonc declares.
declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    COVERS: R2Bucket;
    SESSION_SECRET: string;
    TEST_MIGRATIONS: import('cloudflare:test').D1Migration[];
  }
}
